sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t bwillou/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true bwillou/docker-react-demo npm run test